name: myESLfriends
favicon: null
layout_spectrum: 0.622502168873325
typography_spectrum: 0.11065866239368916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2041612365283072
  lightness: 0.4151814242359251
  saturation: 0.575127902906388
  rhythmicContrast: 0.2655822259839624
purpose: []
